version: "3.9"
services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - TZ=Asia/Taipei
      - GF_SECURITY_ADMIN_USER=$GF_ADMIN
      - GF_SECURITY_ADMIN_PASSWORD=$GF_ADMIN_PASS
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "$HOST_IP:3000:3000"
    networks:
      - lamp

  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./conf/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mqtt/data:/mosquitto/data
      - ./log/mqtt/mosquitto.log:/mosquitto/log/mosquitto.log
    ports:
      - "$HOST_IP:$HOST_PORT:1883"
  db:
    image: postgres:latest
    restart: always
    environment:
      - TZ=Asia/Taipei
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - lamp
networks:
  lamp: