version: "3.9"
services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_ADMIN
      - GF_SECURITY_ADMIN_PASSWORD=$GF_ADMIN_PASS
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "$MQTT_HOST:3000:3000"
    networks:
      - lamp
    depends_on:
      - backend
      - db
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./conf/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mqtt/data:/mosquitto/data
      # - ./log/mqtt/mosquitto.log:/mosquitto/log/mosquitto.log
    ports:
      - "$MQTT_HOST:$MQTT_PORT:1883"
    networks:
      - lamp
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
    expose:
      - 5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - lamp
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    ports:
      - "$FLASK_HOST:$FLASK_PORT:5000"
    networks:
      - lamp
    depends_on:
      - mqtt
  mqtt2db:
    build: ./mqtt2db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASS=$POSTGRES_PASS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    networks:
      - lamp
    depends_on:
      - mqtt
      - db
networks:
  lamp:
